# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.12.0

pipelines:
  default:
    - step:
        script: 
        - git push https://heroku:def0a581-a265-43f8-93f9-dea731c3fc60@git.heroku.com/arcane-dawn-98015.git HEAD